#!syntax bash

# Reset sxhkd
super + shift + s
	pkill -10 sxhkd

# Open terminal
super + Return
	$TERMINAL

# Kill X server
super + control + q
	pkill xinit

# Force kill current program
super + shift + q
	kill -9 $(xdotool getwindowfocus getwindowpid)

# Control audio
super + equal
	pamixer -i 5 --allow-boost
super + minus
	pamixer -d 5 --allow-boost
super + plus
	pamixer -t

# Control backlight
XF86MonBrightnessUp
	light +
XF86MonBrightnessDown
	light -

# Toggle picom
super + shift + c
	if pgrep picom; then pkill picom ; else picom -b ; fi

# Open dmenu_recency
super + d
	dmenu_recency

# Open browser
super + w
	firefox

super + shift + w
	qutebrowser

# Open pulsemixer
super + a
	$TERMINAL -e pulsemixer

# Open htop
super + shift + h
	$TERMINAL -e htop

# Open Vifm
super + v
	$TERMINAL -e vifm

# Open PCManFm
super + shift + v
	pcmanfm

# Run screen script
super + s
	screen

# Vimwiki
super + n
	$TERMINAL -e nvim -c VimwikiIndex

# Autoclicker
super + KP_Insert
	if pgrep autoclicker; then pkill autoclicker & else autoclicker; fi
super + KP_Delete
	time=0.1 autoclicker

@Print
	cd ~/Pictures && scrot
