#!syntax bash

# Reset sxhkd
super + shift + s
	pkill -10 sxhkd

# Open terminal
super + Return
	$TERMINAL

# Open text editor with sxhkrc
super + slash
	$TERMINAL -e nvim ~/.config/sxhkd/sxhkdrc
# Kill X server
super + control + q
	pkill xinit

# kill window
# super + q
# 	xdo close $(xdo id)

# toggle fullscreen
super + shift + f
	xdotool getwindowfocus windowstate --toggle FULLSCREEN

# Force kill current program
super + shift + q
	kill -9 $(xdotool getwindowfocus getwindowpid)

# Control audio volume
XF86AudioRaiseVolume
	pamixer -i 5
XF86AudioLowerVolume
	pamixer -d 5
XF86AudioMute
	pamixer -t

super + equal
	pamixer -i 5 --allow-boost
super + minus
	pamixer -d 5 --allow-boost
super + plus
	pamixer -t

# Control backlight
XF86MonBrightnessUp
	light +
XF86MonBrightnessDown
	light -

# Manage networking
super + n
	networkmanager_dmenu
# Toggle picom
super + shift + c
	if pgrep picom; then pkill picom ; else picom -b ; fi

# Open program
super + d
	dmenu_recency
super + p
	rofi -show drun

# Open browser
super + w
	chromium

super + shift + w
	qutebrowser

# Buku fast open
super + shift + b
	buku-fast --rofi

# Open pulsemixer
super + a
	$TERMINAL -e pulsemixer

# Open htop
super + shift + h
	$TERMINAL -e htop

# Open Vifm
super + v
	$TERMINAL -e vifm

# Open PCManFm
super + shift + v
	pcmanfm

# Run screen script
super + s
	screen

# Change keyboard layout
super + shift + m
	key_menu

# Vimwiki
super + shift + n
	$TERMINAL -e nvim -c VimwikiIndex

# Autoclicker
super + KP_Insert
	if pgrep autoclicker; then pkill autoclicker & else autoclicker; fi
super + KP_Delete
	time=0.1 autoclicker

@Print
	cd ~/Pictures && scrot

# Open togame launcher
super + shift + g
	togame -d
