#!/bin/bash

alias ,f="$EDITOR $BASH_FOLDER/*-functions"

vifm()
{
	local dst="$(command vifm --choose-dir - "$@")"
	if [ -z "$dst" ]; then
		echo 'Directory picking cancelled/failed'
		return 1
	fi
	cd "$dst"
}

shfm () { 
    cd $(command shfm "$@")
}

mkcdir () {
	mkdir -p -- "$1"
	cd -P -- "$1"
}

where () {
	hash "$@" 2> /dev/null
	hash -t "$@" 2> /dev/null
}

isexec () { hash "$@" 2> /dev/null; }

isint () { [ "$1" -eq "$1" ] 2> /dev/null; }

vimwiki () {
	if [[ $# == 0 ]]
	then
	nvim +'VimwikiIndex'
	elif [[ $1 == 'git' ]]
	then
	git -C ~/vimwiki/ ${@:2}
	else
	echo 'Usage: vimwiki [git] [args ...]'
	fi
}

quote () {
	local quoted=${1//\'/\'\\\'\'};
	printf "'%s'" "$quoted"
}
dequote () {
	eval printf %s "$1" 2> /dev/null
}
