#!/bin/bash

alias ,p="$EDITOR $BASH_FOLDER/*-path"

appendpath () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            PATH="$1:$PATH"
    esac
}

appendpath "$HOME/git/scripts"
appendpath "$HOME/go/bin"
appendpath "$HOME/bin"
appendpath "$HOME/Games"
appendpath "$HOME/.local/bin"
